version: 2
updates:

# We do not set open-pull-requests-limit, as sometimes
# dependabot thinks the limit is hit without actually having
# any PRs open. In reality, the configs below can only result
# in at most one PR per package ecosystem anyway.
# A weekly update of the rust-vmm-ci submodule
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
    day: friday

# A weekly update to rust dependencies.
# Using smaller groups to avoid BadObjectState errors with large grouped updates.
# See: https://github.com/dependabot/dependabot-core/issues/10280
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: friday
  groups:
    # Minor and patch updates for production dependencies
    rust-minor-patch:
      dependency-type: "production"
      update-types:
        - "minor"
        - "patch"

    # Development dependencies (build, dev, test)
    rust-dev-dependencies:
      dependency-type: "development"
      update-types:
        - "minor"
        - "patch"

    # Major version updates (potentially breaking changes)
    rust-major-updates:
      update-types:
        - "major"
