[package]
name = "igvmmeasure"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, default-features = true, features = ["derive"] }
igvm_defs.workspace = true
igvm.workspace = true
zerocopy.workspace = true
hmac-sha512.workspace = true

[lints]
workspace = true
